//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCT.Monitor.Server.App_GlobalResources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutAs {
            get {
                return ResourceManager.GetString("AboutAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        internal static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administering.
        /// </summary>
        internal static string Administering {
            get {
                return ResourceManager.GetString("Administering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search.
        /// </summary>
        internal static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertise.
        /// </summary>
        internal static string Advertise {
            get {
                return ResourceManager.GetString("Advertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All dates after.
        /// </summary>
        internal static string AllDatesAfter {
            get {
                return ResourceManager.GetString("AllDatesAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All dates before.
        /// </summary>
        internal static string AllDatesBefore {
            get {
                return ResourceManager.GetString("AllDatesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money.
        /// </summary>
        internal static string AmountOfMoney {
            get {
                return ResourceManager.GetString("AmountOfMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonim.
        /// </summary>
        internal static string AnonimousUser {
            get {
                return ResourceManager.GetString("AnonimousUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article description:.
        /// </summary>
        internal static string ArticleDescription {
            get {
                return ResourceManager.GetString("ArticleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article description can&apos;t be empty!.
        /// </summary>
        internal static string ArticleDescriptionNeededQuery {
            get {
                return ResourceManager.GetString("ArticleDescriptionNeededQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image for article.
        /// </summary>
        internal static string ArticleImage {
            get {
                return ResourceManager.GetString("ArticleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create article without image..
        /// </summary>
        internal static string ArticleImageRequired {
            get {
                return ResourceManager.GetString("ArticleImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article search.
        /// </summary>
        internal static string ArticleSearch {
            get {
                return ResourceManager.GetString("ArticleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article text:.
        /// </summary>
        internal static string ArticleText {
            get {
                return ResourceManager.GetString("ArticleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article text can&apos;t be empty!.
        /// </summary>
        internal static string ArticleTextNeededQuery {
            get {
                return ResourceManager.GetString("ArticleTextNeededQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        internal static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to article.
        /// </summary>
        internal static string BackToArticle {
            get {
                return ResourceManager.GetString("BackToArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best incomes.
        /// </summary>
        internal static string BestIncomes {
            get {
                return ResourceManager.GetString("BestIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized and cann&apos;t live comments..
        /// </summary>
        internal static string CannotCreateComments {
            get {
                return ResourceManager.GetString("CannotCreateComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found.
        /// </summary>
        internal static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose date range.
        /// </summary>
        internal static string ChoseDateRange {
            get {
                return ResourceManager.GetString("ChoseDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed email.
        /// </summary>
        internal static string CloseEmail {
            get {
                return ResourceManager.GetString("CloseEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of comments.
        /// </summary>
        internal static string CommentCount {
            get {
                return ResourceManager.GetString("CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average mark:.
        /// </summary>
        internal static string CommonMark {
            get {
                return ResourceManager.GetString("CommonMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactAs {
            get {
                return ResourceManager.GetString("ContactAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact info.
        /// </summary>
        internal static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create article.
        /// </summary>
        internal static string CreateArticle {
            get {
                return ResourceManager.GetString("CreateArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CreateComment {
            get {
                return ResourceManager.GetString("CreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} at {1}.
        /// </summary>
        internal static string CreatedDate_sDate_sTime {
            get {
                return ResourceManager.GetString("CreatedDate_sDate_sTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create site.
        /// </summary>
        internal static string CreateSite {
            get {
                return ResourceManager.GetString("CreateSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date range.
        /// </summary>
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Sunday&apos;, &apos;Monday&apos;, &apos;Tuesday&apos;, &apos;Wednesday&apos;, &apos;Thursday&apos;, &apos;Friday&apos;, &apos;Saturday&apos;].
        /// </summary>
        internal static string DayNames {
            get {
                return ResourceManager.GetString("DayNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Su&apos;, &apos;Mo&apos;, &apos;Tu&apos;, &apos;We&apos;, &apos;Th&apos;, &apos;Fr&apos;, &apos;Sa&apos;].
        /// </summary>
        internal static string DayNamesMin {
            get {
                return ResourceManager.GetString("DayNamesMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this article and all it,s comments?.
        /// </summary>
        internal static string DeleteArticleQuery {
            get {
                return ResourceManager.GetString("DeleteArticleQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this category and remove it from all articles.
        /// </summary>
        internal static string DeleteCategoryQuery {
            get {
                return ResourceManager.GetString("DeleteCategoryQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this comment?.
        /// </summary>
        internal static string DeleteCommentQuery {
            get {
                return ResourceManager.GetString("DeleteCommentQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete site.
        /// </summary>
        internal static string DeleteSite {
            get {
                return ResourceManager.GetString("DeleteSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this tag and remove it from all articles?.
        /// </summary>
        internal static string DeleteTagQuery {
            get {
                return ResourceManager.GetString("DeleteTagQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this user and all it&apos;s articles and comments?.
        /// </summary>
        internal static string DeleteUserQuery {
            get {
                return ResourceManager.GetString("DeleteUserQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed.
        /// </summary>
        internal static string Detailed {
            get {
                return ResourceManager.GetString("Detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation master greets you.
        /// </summary>
        internal static string DonateMaster {
            get {
                return ResourceManager.GetString("DonateMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this article is very useful you can {0}.
        /// </summary>
        internal static string DonateRequest_sLink {
            get {
                return ResourceManager.GetString("DonateRequest_sLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks you for donation!.
        /// </summary>
        internal static string DonationThanks {
            get {
                return ResourceManager.GetString("DonationThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit article.
        /// </summary>
        internal static string EditArticle {
            get {
                return ResourceManager.GetString("EditArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 hours.
        /// </summary>
        internal static string For24Hours {
            get {
                return ResourceManager.GetString("For24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ForAll {
            get {
                return ResourceManager.GetString("ForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For date.
        /// </summary>
        internal static string ForDate {
            get {
                return ResourceManager.GetString("ForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string ForMonth {
            get {
                return ResourceManager.GetString("ForMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string ForWeek {
            get {
                return ResourceManager.GetString("ForWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string ForYear {
            get {
                return ResourceManager.GetString("ForYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move article to drafts.
        /// </summary>
        internal static string HideArticle {
            get {
                return ResourceManager.GetString("HideArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move this article to drafts?.
        /// </summary>
        internal static string HideArticleQuery {
            get {
                return ResourceManager.GetString("HideArticleQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeLink {
            get {
                return ResourceManager.GetString("HomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install script.
        /// </summary>
        internal static string InstallScript {
            get {
                return ResourceManager.GetString("InstallScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests.
        /// </summary>
        internal static string Interests {
            get {
                return ResourceManager.GetString("Interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string LastActivitiDate {
            get {
                return ResourceManager.GetString("LastActivitiDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last logged in at {0}, {1}.
        /// </summary>
        internal static string LastActivity_sDate_sTime {
            get {
                return ResourceManager.GetString("LastActivity_sDate_sTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last updated at.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        internal static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempting to live the page. All unsaved changes will be lost. Are you sure in you chose?.
        /// </summary>
        internal static string LivePageQuery {
            get {
                return ResourceManager.GetString("LivePageQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load....
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on.
        /// </summary>
        internal static string Logon {
            get {
                return ResourceManager.GetString("Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked as:.
        /// </summary>
        internal static string MarkedAs {
            get {
                return ResourceManager.GetString("MarkedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        internal static string Moderator {
            get {
                return ResourceManager.GetString("Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;January&apos;, &apos;February&apos;, &apos;March&apos;, &apos;April&apos;, &apos;May&apos;, &apos;June&apos;, &apos;July&apos;, &apos;August&apos;, &apos;September&apos;, &apos;October&apos;, &apos;November&apos;, &apos;December&apos;].
        /// </summary>
        internal static string MonthNames {
            get {
                return ResourceManager.GetString("MonthNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most commented.
        /// </summary>
        internal static string MostCommented {
            get {
                return ResourceManager.GetString("MostCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most read.
        /// </summary>
        internal static string MostRead {
            get {
                return ResourceManager.GetString("MostRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who wrote more then other.
        /// </summary>
        internal static string MostWriting {
            get {
                return ResourceManager.GetString("MostWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My articles.
        /// </summary>
        internal static string MyArticles {
            get {
                return ResourceManager.GetString("MyArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next range.
        /// </summary>
        internal static string NextLinkText {
            get {
                return ResourceManager.GetString("NextLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        internal static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no new articles for this period!&lt;br/&gt; Write it and be here!.
        /// </summary>
        internal static string NoArticles {
            get {
                return ResourceManager.GetString("NoArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You also can find some articles by this tags cloude!.
        /// </summary>
        internal static string NoArticlesAditionalAction {
            get {
                return ResourceManager.GetString("NoArticlesAditionalAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no comments for this article. Be first!.
        /// </summary>
        internal static string NoComments {
            get {
                return ResourceManager.GetString("NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no drafts.
        /// </summary>
        internal static string NoDraftArticles {
            get {
                return ResourceManager.GetString("NoDraftArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no published articles.
        /// </summary>
        internal static string NoPublishedArticles {
            get {
                return ResourceManager.GetString("NoPublishedArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing has found for your request.
        /// </summary>
        internal static string NoSearchResult {
            get {
                return ResourceManager.GetString("NoSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page of user.
        /// </summary>
        internal static string PageOfUser {
            get {
                return ResourceManager.GetString("PageOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous range.
        /// </summary>
        internal static string PrevLinkText {
            get {
                return ResourceManager.GetString("PrevLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to publish this article?.
        /// </summary>
        internal static string PublishArticleQuery {
            get {
                return ResourceManager.GetString("PublishArticleQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published {0} at {1}.
        /// </summary>
        internal static string PublishedDate_sDate_sTime {
            get {
                return ResourceManager.GetString("PublishedDate_sDate_sTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published by {0} {1} at {1}.
        /// </summary>
        internal static string PublishedDate_sName_sDate_sTime {
            get {
                return ResourceManager.GetString("PublishedDate_sName_sDate_sTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher name.
        /// </summary>
        internal static string PublisherName {
            get {
                return ResourceManager.GetString("PublisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RangeEndTitle {
            get {
                return ResourceManager.GetString("RangeEndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RangeStartTitle {
            get {
                return ResourceManager.GetString("RangeStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reads.
        /// </summary>
        internal static string ReadCount {
            get {
                return ResourceManager.GetString("ReadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        internal static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and continue.
        /// </summary>
        internal static string SaveAndContinue {
            get {
                return ResourceManager.GetString("SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string SaveAndPublish {
            get {
                return ResourceManager.GetString("SaveAndPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to drafts.
        /// </summary>
        internal static string SaveDraft {
            get {
                return ResourceManager.GetString("SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serch by categories.
        /// </summary>
        internal static string SearchByCategories {
            get {
                return ResourceManager.GetString("SearchByCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by date range.
        /// </summary>
        internal static string SearchByDateRange {
            get {
                return ResourceManager.GetString("SearchByDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by nickname.
        /// </summary>
        internal static string SearchByNickName {
            get {
                return ResourceManager.GetString("SearchByNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by tags.
        /// </summary>
        internal static string SearchByTags {
            get {
                return ResourceManager.GetString("SearchByTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in caption.
        /// </summary>
        internal static string SearchInCaption {
            get {
                return ResourceManager.GetString("SearchInCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in description.
        /// </summary>
        internal static string SearchInDescription {
            get {
                return ResourceManager.GetString("SearchInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in text.
        /// </summary>
        internal static string SearchInText {
            get {
                return ResourceManager.GetString("SearchInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About your-self.
        /// </summary>
        internal static string SelfDescription {
            get {
                return ResourceManager.GetString("SelfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to mark this article with .
        /// </summary>
        internal static string SetMarkQuery {
            get {
                return ResourceManager.GetString("SetMarkQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habr-Habr.
        /// </summary>
        internal static string SiteCaption {
            get {
                return ResourceManager.GetString("SiteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site creation.
        /// </summary>
        internal static string SiteCreation {
            get {
                return ResourceManager.GetString("SiteCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site domain.
        /// </summary>
        internal static string SiteDomain {
            get {
                return ResourceManager.GetString("SiteDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name.
        /// </summary>
        internal static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site pages.
        /// </summary>
        internal static string SitePages {
            get {
                return ResourceManager.GetString("SitePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort result by.
        /// </summary>
        internal static string SortResultBy {
            get {
                return ResourceManager.GetString("SortResultBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific date.
        /// </summary>
        internal static string SpecificDate {
            get {
                return ResourceManager.GetString("SpecificDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags cloud.
        /// </summary>
        internal static string TagCloud {
            get {
                return ResourceManager.GetString("TagCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount of money you earned is .
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users count.
        /// </summary>
        internal static string UserCount {
            get {
                return ResourceManager.GetString("UserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mark:.
        /// </summary>
        internal static string UserMark {
            get {
                return ResourceManager.GetString("UserMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User search.
        /// </summary>
        internal static string UserSearch {
            get {
                return ResourceManager.GetString("UserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string UserSurname {
            get {
                return ResourceManager.GetString("UserSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcome.
        /// </summary>
        internal static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was writen:.
        /// </summary>
        internal static string Writen {
            get {
                return ResourceManager.GetString("Writen", resourceCulture);
            }
        }
    }
}
